### ISSUE TITLE
Login & Register redirect issue 

### ISSUE THREAD

**Issue by IrealiTY** [axl6409/tvo-spa#8]
Hi :)
I'm trying to set up your project but run into the issue that when I click "register", the Bungie login pops up - and after logging in in it, the windows redirects me to the same login page and it also never adds any user to the MySQL db either.

I wonder if something is wrong in my config.

I did enter the OAuth client_id, OAuth client_secret and the Bungie API key in the `.env` file. But I feel like my Redirect URL on Bungie's website is wrong
![image](https://user-images.githubusercontent.com/1223686/97105590-50314100-16bc-11eb-976c-457217f2e0fd.png)

Any chance you could point me into the right direction?

**Comment by axl6409** [comment]
For a local usage you need tu set the path to your project only with that
"*", on the bungie api settings

**Comment by IrealiTY** [comment]
Hm :/
My domain is https://latreia.team
If I use  https://latreia.team/* or  https://latreia.team/"*" (just to test) 
I result in "Page not found"
![image](https://user-images.githubusercontent.com/1223686/97115971-868db100-16fa-11eb-8f96-93c55ccd4736.png)

**Comment by axl6409** [comment]
No only this symbol * and nothing else. Remember it's just if you run it in
local

**Comment by axl6409** [comment]
I check tomorow my configuration and i tell you wich posibilities you can
try
;)

**Comment by IrealiTY** [comment]
Oh yeah I'm not "Local" hosted FYI :)

**Comment by IrealiTY** [comment]
Désolé de remettre ça sur la table :) Did you happen to have a chance to have a look at the config?

**Comment by axl6409** [comment]
Hi ! I'm sorry for being late !
For the Redirect Url i put :
https://yourname.com/api/oauth/bungie/callback

Try this and tell me if it's OK ;)

**Comment by IrealiTY** [comment]
It did not :( But atleast it gave a error message:

```
[22:03:21] LOG.error: Client error: `POST https://www.bungie.net/platform/app/oauth/token/` resulted in a `400 Bad Request` response:
{"error":"invalid_request","error_description":"redirect_uri does not match application configuration."}
 {"exception":{}}
```

![image](https://user-images.githubusercontent.com/1223686/97924427-ed951080-1d5f-11eb-93c2-f6786abda741.png)

**Comment by axl6409** [comment]
Did you copy the right file BungieCustomProvider.php in the right socialite
folder ?
And did you follow all the steps for initialisations ?

**Comment by IrealiTY** [comment]
Pretty sure I did 🤔

I just did a second pass on all the settings and all initialisations steps again just to make sure :/
